### ISSUE TITLE
Is it a bug to get body position?

### ISSUE THREAD

**Issue by chinahuangyong** [deepmind/mujoco#112] opened 2022-01-18 03:06 UTC
Hello, I am use mujoco to simulate the quadruped mini cheetah,  mini cheetah is static, but i get the position from the sensor in mujoco, the position axis x is always Increase.

![mini_cheetah_mujoco](https://user-images.githubusercontent.com/20627061/149863728-7ce4aeba-37d4-4481-8f48-9e485e2b4047.gif)

this is  mini cheetah xml file and stl file.
[mini_cheetah.zip](https://github.com/deepmind/mujoco/files/7885914/mini_cheetah.zip)

**Comment by yuvaltassa** [comment] 2022-01-18 13:40
Hi @chinahuangyong,

This is a bit hard to diagnose, in the model you attached the robot just falls over, so I can't reproduce. Did you remove the joints or add high-gain position actuators? If you send the model where this happens and we could follow up.

In the meantime I recommend turning on force visualisation (hit the 'F' key). For some setting you can get jittering forces which can cause this phenomenon. If that's the case perhaps try switching to elliptic friction cones (in the 'physics' tab) as the are completely isotropic, unlike pyramidal cones.

BTW, this is a nice model, can you point me to where you found it?

**Comment by chinahuangyong** [comment] 2022-01-19 03:56
yeah, i use pd control to control the joint position, the despite position;
```
RF:
x0.q[0] = -0.7;
  x0.q[1] = 1.;
  x0.q[2] = 2.715;
LF:
  x0.q[0] = 0.7;
  x0.q[1] = 1.;
  x0.q[2] = 2.715;

  x0.q[0] = -0.7;
  x0.q[1] = -1.0;
  x0.q[2] = -2.715;

  x0.q[0] = 0.7;
  x0.q[1] = -1.0;
  x0.q[2] = -2.715;
```
![image](https://user-images.githubusercontent.com/20627061/150061230-6240b1ff-61ad-4df0-b1a5-1dd3708aada0.png)

the model is convert urdf file to xml file, and add some constraint and others.

**Comment by yuvaltassa** [comment] 2022-01-19 23:29
Could you please make a model that shows this behaviour upon load in `simulate` without any additional code?
You can add position actuators using [`<position joint="joint_name" kp="gain"/>`](https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-position) (you probably want more damping in your joints btw), and you can change the semantics of your joints angles using [`<joint ref="refangle"/>`](https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-joint), such that the zero controls upon load will take the joints to `-refangle`

Thanks

**Comment by saran-t** [comment] 2022-03-18 23:38
Closing since there hasn't been a response for a while. Please reopen if required.

**Closed by saran-t** 2022-03-18 23:38 UTC
