### ISSUE TITLE
Binary for Apple chip?

### ISSUE THREAD

**Issue by shuvoxcd01** [deepmind/mujoco#90] opened 2021-12-15 13:35 UTC
Hi,
Will there be a binary for the apple-chip-based macs soon?

**Comment by matte-esse** [comment] 2021-12-16 16:24
The main issues was just closed, https://github.com/deepmind/mujoco/issues/2 the new version has been released.

However before this issues is closed too I wanted to ask if it's all ready to be run using python or if we have to wait for an updated of the python library https://pypi.org/project/mujoco-py/#history and if we have to wait for a release on MuJoCo website https://mujoco.org/download

**Comment by matte-esse** [comment] 2021-12-16 17:05
Duplicate of #2

**Comment by saran-t** [comment] 2021-12-16 18:34
Closing this as a duplicate, let's continue the discussion in #2

**Closed by saran-t** 2021-12-16 18:34 UTC
