### ISSUE TITLE
Estimated ETA for M1 compatibility?

### ISSUE THREAD

**Issue by testt-1** [deepmind/mujoco#69] opened 2021-11-20 23:32 UTC
Hi! I know this has been asked before, but is there an estimate? Or at least will it be anytime soon?

**Comment by matte-esse** [comment] 2021-11-23 14:35
I asked on the main issue but I wasn't give any answer yet.

**Comment by saran-t** [comment] 2021-11-24 14:54
Duplicate of #2 (update provided in that issue)

**Closed by saran-t** 2021-11-24 14:54 UTC
