### ISSUE TITLE
How to set the collision volume of the model in XML

### ISSUE THREAD

**Issue by forcywan** [deepmind/mujoco#939] opened 2023-06-20 05:41 UTC
Hi,

I'm a student and I'm trying to use MuJoCo for robot.

Here is a model which explains my question:

```XML
        <body name="guandao"  pos="0 0 0.5">
              <geom type="mesh"  mesh="guandao"  friction="1 0.05 0.01"/>
        </body>
        <body name="LK6" pos="0.074174 -0.0015 -0.026955">
            <inertial pos="0.046051 0.0028057 0.019746" quat="0.695924 -0.163384 -0.172525 0.677665" mass="0.059808" 
               diaginertia="3.20184e-05 2.8093e-05 2.56056e-05" />
            <joint name="LJ6" pos="0 0 0" axis="0 -1 0" />
            <geom type="mesh" contype="0" conaffinity="0" group="1" rgba="1 1 1 1" mesh="LK6" />
            <geom type="mesh" rgba="1 1 1 1" mesh="LK6" />
        </body>
```
I exported a mesh file of the pipeline from solidwork. When imported into mujoco, the inside of the pipe has a wall of air, like a solid cylinder, which the robot can't move through.
Thank u!

**Comment by kevinzakka** [comment] 2023-06-21 07:01
Duplicate of #938.

**Closed by kevinzakka** 2023-06-21 07:01 UTC
Labels: question
